create table coach_info
(
    id           integer generated by default as identity,
    availability varchar(255),
    introduction varchar(255),
    primary key (id)
);

alter table coach_info
    owner to student;

create unique index coach_info_id_index
    on coach_info (id);


create table coach_topic
(
    id               integer generated by default as identity,
    experience_level integer,
    topic_name       varchar(255),
    fk_coach_info_id integer,
    primary key (id)
);

alter table coach_topic
    owner to student;

alter table coach_topic
    add constraint fk_coach_info_id foreign key (fk_coach_info_id) references coach_info;

create unique index coach_topic_id_index
    on coach_topic (id);


create table users
(
    id            integer generated by default as identity,
    email         varchar(255),
    first_name    varchar(255),
    last_name     varchar(255),
    password      varchar(255),
    role          varchar(255),
    coach_info_id integer,
    primary key (id)
);

alter table users
    owner to student;

alter table users
    add constraint coach_info_id foreign key (coach_info_id) references coach_info;

create unique index users_id_index
    on users (id);





